# Plugin version - do not change!
plugin-version: "1.0.1"
# Title of the Server Selector GUI window
title: "Choose a server:"
# Size of the GUI (valid sizes: 54 (double chest), 27 (single chest))
gui-size: 54
# Allow players to close the GUI
allow-closing: false
# Inventory item that opens the GUI (deactivated if 'allow-closing' is false)
selector-item: "ENDER_PEARL"
selector-name: "Servers"
selector-slot: 4

# Message displayed when leaving the server
disconnect-message: "Bye!"
# List of servers players can join
servers:
  10:
    name: "Example Server"
    proxy-name: "example"
    item: "REDSTONE_BLOCK"
    lore:
      - "Example text"
      - "Multiple lines!"