# Title of the Server Selector GUI window
title: "Choose a server:"
# Message displayed when leaving the server
disconnect-message: "Bye!"
# List of servers players can join
servers:
  10:
    name: "Example Server"
    proxy-name: "example"
    item: "REDSTONE_BLOCK"