# Title of the Server Selector GUI window
title: "Choose a server:"
# Message displayed when leaving the server
disconnect-message: "Bye!"
servers:
  10:
    name: "Example Server"
    item: "REDSTONE_BLOCK"
    host: "127.0.0.1"
    port: 25565